project:
  type: website

website:
  title: "Chris Hires"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
  google-analytics: "G-LJ3R753XPB"

format:
  html:
    toc: true
    code-fold: true
    code-summary: "Show Code"
    css: styles.css



